env:
  global:
    - test_variable_one=$(if [ 1 == 1 ]; then echo true; else echo false; fi)
    - test_variable_two=$(if [ 1 == 2 ]; then echo true; else echo false; fi)
    - test_variable_three=$(if [ 1 == whateva ]; then echo true; else echo false; fi)
jobs:
  include:
    - name: Test 1 with = 'true' condition
      script:
        - echo "Hello world" && echo "Test 1 has been run"
      if: env(test_variable_one)='true'
    - name: Test 2 with = true condition
      script:
        - echo "Hello world" && echo "Test 2 has been run"
      if: env(test_variable_two)=true
    - name: Test 3 with IS true condition
      script:
        - echo "Hello world" && echo "Test 2 has been run"
      if: env(test_variable_three) IS true
    - name: Test 4 equating to complete bash liner
      script:
        - echo "Hello world" && echo "Test 2 has been run"
      if: env(test_variable_three) = '$(if [ 1 == whateva ]; then echo true; else echo false; fi)'